services:
  bot:
    platform: linux/amd64
    build: .
    image: siegfriedschmidt/telegram-user-bot
    container_name: telegram-post-bot
    environment:
      - SECRET_FOLDER=/app/secret
    volumes:
      - ./secret:/app/secret

    restart: "no"